### ISSUE TITLE
[xcam][master][CL] When export OCL_TILING=2, video has ghost with encoder

### ISSUE THREAD

**Issue by liuyinhx** [01org/libxcam#139]
Title:
  [xcam][0.2/master/0.2.1][CL]

Contents:
  BSP: Yocto-linux
  Version: Libxcam 0.2.1
  HW: rubypark
  Regression: no

Reproduce steps:
  1. deploy the image to rubypark device
  2. run mediapipe
  3. run VLC to access IPCamera

Expect and current result:
  The preview should be normal, but video has ghost with encoder.

Bug description:
  When export OCL_TILING=2 in terminal, video has ghost with encoder.

**Comment by liuyinhx** [comment]
Cannot reproduce, close this issue.

**Comment by zjamy** [comment]
fixed by wind.
