### ISSUE TITLE
[xcam][master][CL] Preview failure when Open HDR and TNR-lab at the same time

### ISSUE THREAD

**Issue by liuyinhx** [01org/libxcam#154]
Title:
[xcam][0.2.1/master/0.3][CL] Preview failure when Open HDR and TNR-lab at the same time

Contents:
BSP: Yocto-Linux
Version: Libxcam 0.2.1
HW: rubypark
Regression: yes, in 0717's image, it's ok.

Reproduce steps:
1. deploy the image to rubypark device
2. open HDR and TNR-lab in config files 
3. run command:
    test-device-manager -m dma -c -f BA10 -d still -p -a dynamic

Expect and current result:
    Open HDR and TNR-lab at the same time, the preview should be normal.

Bug description:
    The preview will be stuck when Open HDR and TNR-lab at the same time.

**Comment by wang-fei** [comment]
fixed
