### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [01org/libxcam#173]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/01org/libxcam/blob/c2f1908d387badffc60758df8e919eab2c03e657/configure.ac#L94 "Configuration checks")?

**Comment by zjamy** [comment]
not familiar with this configuration, but we will check this later. thanks for suggestion

**Comment by elfring** [comment]
Should this issue be kept open until the affected implementation details will be improved?
