### ISSUE TITLE
[xcam][master][ISP] Compile failed if disable aiq

### ISSUE THREAD

**Issue by liuyinhx** [01org/libxcam#190]
Title:
  [xcam][0.2.1/master/0.3][ISP] Compile failed if disable aiq

Contents:
BSP: Yocto-Linux or 64-bit linux
Version: Libxcam 0.2.1
HW: rubypark
Regression: new issue

Reproduce steps:
  1. $ ./configure --disable-aiq
  2. $ make

Expect and current result:
  The compile should succeed.

Bug description:
  error info:
        ../xcore/.libs/libxcam_core.so: undefined reference to `XCam::X3aAnalyzerAiq::X3aAnalyzerAiq(atomisp_sensor_mode_data&, char const*)'
    ../xcore/.libs/libxcam_core.so: undefined reference to `XCam::HybridAnalyzer::HybridAnalyzer(_XCam3ADescription*, XCam::SmartPtr<XCam::AnalyzerLoader>&, XCam::SmartPtr<XCam::IspController>&, char const*)'
    collect2: error: ld returned 1 exit status

**Comment by skibey** [comment]
submitted pull request to fix this:
https://github.com/01org/libxcam/pull/200

Tested on rubypark and Ubuntu.

**Comment by liuyinhx** [comment]
fixed
