### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [01org/libxcam#209]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [a function like "xcam_destroy_context"](https://github.com/01org/libxcam/blob/e17a6a6c328d84c3938fd8aab45dd4d5d6b0d4ed/3alib/hybrid/sample.cpp#L57 "xcam_destroy_context function").

**Comment by zongwave** [comment]
Fixed

**Comment by zongwave** [comment]
Fixed

**Comment by elfring** [comment]
Which commit does contain corresponding software changes?
