### ISSUE TITLE
About gamma table setting?

### ISSUE THREAD

**Issue by cherixy** [01org/libxcam#343]
According src of libxcam, there are three gamma tables which are  r_gamma，g_gamma and b_gamma. However I can only generate one gamma table with Intel IQ Tool. So, I don't know how I use this table from Intel IQ Tool to set the gamma paramter into libxcam. Are there any points for my problem? Thank you~~

**Comment by windyuan** [comment]
most of the time, gamma is set for improve brightness. you can set r/g/b gamma the same table.

**Comment by cherixy** [comment]
@windyuan  OK， I get it, Thank you~~  My team wants to use auto-aperture based on libxcam.  I just find that it provides the interface of "set_aperture". This interface can't be used to accomplish auto-aperture. Will libcam support auto-aperture? And can you provide any testing gamma table for me？

**Comment by windyuan** [comment]
sorry, set_aperture is not supported by now. actually it depends on driver which is not in our scope.
gamma table you can try gamma=1.5~2.2 and generate a table.

**Comment by cherixy** [comment]
@windyuan  Attaced files is generated from IQ Tool based on my imx185_cpf. Where can I modify gamma=1.5~2.2 to generate a table again?
![gamma_table](https://cloud.githubusercontent.com/assets/17023290/17400801/98fa1296-5a7c-11e6-9bc9-1ccbb6127a9c.png)

**Comment by windyuan** [comment]
no idea about IQ tool tuning, it's out of our scope. suggest you to contact this tool author or people who give you this tool.
a simple example is that you can write a C program to generate gamma table. you can search online.

**Comment by cherixy** [comment]
@windyuan  Thank you very much

**Comment by dsrsan** [comment]
@cherixy  Dear cherixy, please can you provide us the Intel contact who gave you access to the IQ tool?
Is there a way we can get in contact with you via e-mail, we are also working on IMX185.
Best Regards.
