### ISSUE TITLE
gbe_bin_generater offline compiler occurs  assert error

### ISSUE THREAD

**Issue by avansguo** [01org/libxcam#388]
root@kzsmartipc:/tmp# ./gbe_bin_generater kernel_csc_nv12torgba.cl  -o kernel_csc_nv12torgba.cl.bin -t 0x0f31
ASSERTION FAILED: sel.hasDoubleType()
  at file /home/guoqiang/code/git_code/master/IPC/libOpenSource/Trunk/src/Beignet-1.2.1-Source/backend/src/backend/gen_insn_selection.cpp, function void gbe::ConvertInstructionPattern::convertBetweenFloatDouble(gbe::Selection::Opaque&, const gbe::ir::ConvertInstruction&, bool&) const, line 5110
Trace/breakpoint trap

why & thanks

**Comment by avansguo** [comment]
./gbe_bin_generater kernel_csc_rgbatonv12.cl -o kernel_csc_rgbatonv12.cl.bin -t 0x0f31   
this is success.   the Beignet version is 1.2.1

**Comment by zongwave** [comment]
Could you let us know the beignet version failed to build cl kernel source you used? 

BTW, if you want to compile opencl kernel code into cl binary text, you can try use libxcam tool

test/test-binary-kernel :  source code --> binary
tools/convert-binary-to-text.sh   binary --> binary text

**Comment by avansguo** [comment]
the Beignet version is 1.2.1 
libxcam version is 0.7.0

**Comment by zongwave** [comment]
with the same Beignet version, "kernel_csc_rgbatonv12.cl" can be built successfully, but "kernel_csc_nv12torgba.cl" built failed? the operation used in these two cl source are almost same, do you make any change in these kernel source?

**Comment by avansguo** [comment]
No, I didn't do anything about these kernel source .   
因为我编译好xcam 后， 在我的设备上运行，运行时编译kernel  会报这种错误， 所以才想到先编译试试看， 发现先编译kernel 也会报这种错误。  但是编 kernel_csc_rgbatonv12.cl 就是可以的。

**Comment by avansguo** [comment]
i try  "test-binary-kernel ", but it dont work too.  and the errors is same with "gbe_bin_generater"

root@kzsmartipc:/tmp# ./test-binary-kernel -i kernel_csc_nv12torgba.cl -o kernel_csc_nv12torgba.cl.bin
ASSERTION FAILED: sel.hasDoubleType()
  at file /home/guoqiang/code/git_code/master/IPC/libOpenSource/Trunk/src/Beignet-1.2.1-Source/backend/src/backend/gen_insn_selection.cpp, function void gbe::ConvertInstructionPattern::convertBetweenFloatDouble(gbe::Selection::Opaque&, const gbe::ir::ConvertInstruction&, bool&) const, line 5110
Trace/breakpoint trap

**Comment by guoyejun** [comment]
How to fix:  
add suffix 'f' for all the literal floating numbers, such as 0.5f, 2.03211f.

Why assertion for kernel_csc_nv12torgba.cl on device 0x0f31:
literal floating numbers without 'f' as suffix in opencl kernel is considered as double (opencl c language is based on c language), while 0x0f31 is the hardware without double support.  
There is no issue if we change to a newer hardware for example 0x1912 with double support.

why kernel_csc_rgbatonv12.cl works on 0x0f31:
it happens to be the case that the kernel is optimized and no double support is needed at hardware level.

**Comment by avansguo** [comment]
ok , thank you very much .

**Comment by avansguo** [comment]
there is a new error , info is follow:

XCAM WARNING cl_context.cpp:357: CL build program failed on kernel_bayer_pipe, error_code(-11)  build log:stringInput.cl:98:47: error: can't convert between vector values of different size ('float2' (vector of 2 'float' values) and 'double')
stringInput.cl:98:62: error: can't convert between vector values of different size ('float2' (vector of 2 'float' values) and 'double')

**Comment by guoyejun** [comment]
could you paste the opencl kernel source?

**Comment by avansguo** [comment]
kernel name  : kernel_bayer_pipe

**Comment by guoyejun** [comment]
just add two 'f' as below:
 egain[0] = mad(ee, ee_config.ee_gain, out + 0.03f) / (out + 0.03f);

**Comment by avansguo** [comment]
i found it too ,  thanks

**Comment by windyuan** [comment]
Thank you for @avansguo and @guoyejun pointing out this issue.
We'll check all cl kernels in libxcam to fix the conversion between float and double.

**Comment by windyuan** [comment]
Assign this issue to @liuyinhangx .
Thanks,
Wind

**Comment by liuyinhangx** [comment]
This issue has been fixed by Zong Wei <wei.zong@intel.com>.
commit bacae1c546a604cd0dcf6cc16c9201083d94e9dd
Thanks.

**Comment by windyuan** [comment]
Good. thanks @zongwave.
If verified. please close this issue.
