### ISSUE TITLE
fedora 23 libcl not found

### ISSUE THREAD

**Issue by arpu** [01org/libxcam#397]
fedora 23 

./configure  --enable-libcl  --enable-opencv --enable-debug 

     libxcam configuration summary
     version                    : 0.8.0
     enable debug               : yes
     enable profiling           : no
     build GStreamer plugin     : no
     build aiq analyzer         : no
     use local aiq              : no
     use local atomisp          : yes
     have opencl lib            : no
     have opencv lib            : yes
     enable 3a lib              : no
     enable smart analysis lib  : no

any help what packages are needed?

**Comment by uartie** [comment]
I believe the package is `beignet`.  Try `dnf provides */libcl.so`.

**Comment by arpu** [comment]
ok yes you are right but 

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH                                                                                                                                  
echo $PKG_CONFIG_PATH                                                                                                                                                                  
/usr/local/lib/pkgconfig:/usr/lib/pkgconfig
./configure --enable-libcl --enable-opencv
checking for LIBCL... no
checking for LIBCL... no

locate libcl.so                                                                                                                                                                                     
/usr/lib64/beignet/libcl.so

any idea how i can solve this?

**Comment by uartie** [comment]
Yup, it looks like neither `beignet` nor `beignet-devel` provides a `libcl.pc` file.  I'm not sure where to get it.  @windyuan can you help with this?

**Comment by arpu** [comment]
as workaround 
set HAVE_LIBCL=1 in configure.ac after the libcl check 
and add -lOpenCL to the tests/Makefile

**Comment by windyuan** [comment]
@uartie, sorry for late reply, just came back from Chinese New Year vacation. 
yes, you are right, it's the beignet dependency. currently libxcam code depends on <CL/cl_intel.h> which can be get from `beignet-devel`. `libcl.pc` had ever been used in some other projects.  Your code should go to here

    if test "$enable_libcl" = "yes" && test "$HAVE_LIBCL" -eq 0; then
        PKG_CHECK_MODULES(LIBCL, [OpenCL], [HAVE_LIBCL=1], [HAVE_LIBCL=0])
    fi
which means you have to install OpenCL.pc first.

@arpu ,  thanks for your workaround, force to set `HAVE_LIBCL=1` in configure.ac is not necessary if `OpenCL.pc` was installed. could you submit your patch with OpenCL for tests/Makefile?

Thanks,
Wind Yuan

**Comment by arpu** [comment]
dnf provides OpenCL.pc                                                                                                                                                                         
Last metadata expiration check: 22:08:54 ago on Mon Feb  6 19:44:30 2017.
Error: No Matches found

about the patch i will look at this!

**Comment by windyuan** [comment]
@arpu, thanks.
sorry, I don't have a Fedora OS. In Ubuntu, `OpenCL.pc` is from `ocl-icd-opencl-dev`. you can check ocl-icl related package.

**Comment by arpu** [comment]
works now for me i think the problem was not installed ocl dev  package

**Comment by windyuan** [comment]
thank you.
