### ISSUE TITLE
autogen.sh should run ./configure

### ISSUE THREAD

**Issue by uartie** [01org/libxcam#398]
It is common practice for ./autogen.sh to automatically run ./configure for you.  See intel-vaapi-driver's autogen.sh for an example.

**Comment by windyuan** [comment]
Thank you for pointing out. we'll fix it soon.
currently we don't auto-run ./configure just because sometimes developer want set different environment e.g. `CFLAG=xxxx`. we'll fix it.

**Comment by liuyinhangx** [comment]
I have fixed this issue, new patch: bbb83d0c147f4f617e215e0dc359b8f597e40312

**Comment by liuyinhangx** [comment]
Verified， close this issue.
commit 72ca7c7c1ce47f1170f955dc6ab87f31466d853f
