### ISSUE TITLE
Provide dependency and compile instructions

### ISSUE THREAD

**Issue by uartie** [01org/libxcam#399]
It is not clear what dependencies are required to compile libxcam or where to get them.  Please provide these details in the README.  Although most of this can be extrapolated from configure.ac, it does not always lead to success.  For example, see #397.

**Comment by windyuan** [comment]
Thanks for your suggestion. we'll fix it.

**Comment by liuyinhangx** [comment]
I have fixed this issue, new patch: d9f21f51172c5eae3ff6860f11338fa85d5ed580

**Comment by liuyinhangx** [comment]
Verified， close this issue.
commit 286d04bd9b6abfe4dd7d5d17abb9b34be46d34e7
