### ISSUE TITLE
broken output of test-image-stitching sample

### ISSUE THREAD

**Issue by RomanArzumanyan** [01org/libxcam#424]
test-image-stitching sample produces broken output on Ubuntu 16.04 (i7-6770HQ) with Beignet.
Compiled with OpenCL & OpenCV support & "OCL_TILING=0" symbol exported.
Input & output images enclosed.

![input](https://cloud.githubusercontent.com/assets/6653296/24858205/02d6e42e-1df4-11e7-87e4-41fefa4dfa4d.png)
![stitch](https://cloud.githubusercontent.com/assets/6653296/24858206/02d8df72-1df4-11e7-8f2b-41e13fc58629.png)

**Comment by windyuan** [comment]
@liuyinhangx  will follow up this issue.
what's your cmdline. any more details? we did find this issue in last release.

**Comment by RomanArzumanyan** [comment]
./test-image-stitching \
    --input  /home/roman/Videos/input.nv12 \
    --output /home/roman/Videos/output.mp4

Both input & output have default sizes (1920x1080 and 1920x960 corresp.)

**Comment by liuyinhangx** [comment]
We can't reproduce this issue, could you let us know the opencv version and  beignet version (or the latest commit id).

**Comment by RomanArzumanyan** [comment]
OpenCV 3.2.0
Beignet commit a7dc7692a4f00f33c09a2ad5bc7b58bb9fdd43e5 on master

**Comment by windyuan** [comment]
do you have tools to check /home/roman/Videos/input.nv12 is a correct image? I'm thinking about is it possible input.nv12 is already corrupt.

**Comment by RomanArzumanyan** [comment]
Hi,
Input isn't broken - actually it's attached to 1st message in thread (converted from nv12 to png).

**Comment by liuyinhangx** [comment]
Hi, please try to set OCL_TILING to 0 in the terminal:
$ export OCL_TILING=0

**Comment by RomanArzumanyan** [comment]
Hi,
Exporting solves the issue. Thanks a lot.

**Comment by arpu** [comment]
hello i get some problems too can you upload the image as nv12? to test for me

**Comment by windyuan** [comment]
@arpu if you have png file. you can try gstreamer to convert to NV12.
gst-launch-1.0 filesrc location=in.png ! pngdec  ! videoconvert ! video/x-raw, format=NV12 ! filesink location=out.nv12

if you have Ricoh Theta S camera. you can convert fisheye video mp4 to NV12 by 
gst-launch-1.0 filesrc location=in.mp4 ! qtdemux ! avdec_h264  ! videoconvert ! video/x-raw, format=NV12 ! filesink location=out.nv12

**Comment by arpu** [comment]
@windyuan  thx for this hint! works
