### ISSUE TITLE
config.status: error: cannot find input file: `clx_kernel/Makefile.in'

### ISSUE THREAD

**Issue by arpu** [01org/libxcam#496]
fedora 26 

./configure 
gives me 
config.status: error: cannot find input file: `clx_kernel/Makefile.in'

complete output
http://lpaste.net/7096152959385337856

**Comment by windyuan** [comment]
assign to @liuyinhangx .
we don't have fedora. but we can check it on ubuntu. thanks for reporting this issue.

**Comment by liuyinhangx** [comment]
@arpu , i can't reproduce this issue on ubuntu 16.04, you can try solutions below:
1. rerun autogen.sh to generate Makefile.in
2. if the first solution fails, it may be an installation problem of libtool.

**Comment by arpu** [comment]
@liuyinhangx  you right installing libtool with sudo dnf libtool works now!
